version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
            ICC_DEBUG: 1
            ICC_TESTING: 1
            DATABASE_URL: "mysql+pymysql://python:password@172.19.0.2/icc?charset=utf8mb4"
    mariadb:
        image: "mariadb"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "python"
            MYSQL_PASSWORD: "password"
