version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
            ICC_DEBUG: "TRUE"
            ICC_TESTING: "TRUE"
    mariadb:
        image: "mariadb"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "python"
            MYSQL_PASSWORD: "password"
    elasticsearch:
        image: "elasticsearch:7.8.0"
        ports:
            - 9200:9200
        networks:
            - elastic
networks:
    elastic:
        driver: bridge
