"""empty message

Revision ID: 001c56f6f348
Revises: d68059beaead
Create Date: 2018-10-03 13:19:24.529095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001c56f6f348'
down_revision = 'd68059beaead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('locked', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_annotation_locked'), 'annotation', ['locked'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_locked'), table_name='annotation')
    op.drop_column('annotation', 'locked')
    # ### end Alembic commands ###
