"""empty message

Revision ID: 0a91abb0bd0a
Revises: b6b30b1aff2a
Create Date: 2018-07-21 08:37:28.527267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a91abb0bd0a'
down_revision = 'b6b30b1aff2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('book_num', sa.Integer(), nullable=True),
    sa.Column('part_num', sa.Integer(), nullable=True),
    sa.Column('ch_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_book_id'), 'break', ['book_id'], unique=False)
    op.create_index(op.f('ix_break_book_num'), 'break', ['book_num'], unique=False)
    op.create_index(op.f('ix_break_ch_num'), 'break', ['ch_num'], unique=False)
    op.create_index(op.f('ix_break_part_num'), 'break', ['part_num'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_index(op.f('ix_book_url'), 'book', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_url'), table_name='book')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_break_part_num'), table_name='break')
    op.drop_index(op.f('ix_break_ch_num'), table_name='break')
    op.drop_index(op.f('ix_break_book_num'), table_name='break')
    op.drop_index(op.f('ix_break_book_id'), table_name='break')
    op.drop_table('break')
    # ### end Alembic commands ###
