"""empty message

Revision ID: 0c06324d7840
Revises: 7914b1837739
Create Date: 2018-08-29 19:23:37.938475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c06324d7840'
down_revision = '7914b1837739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_version', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_version', 'approved')
    # ### end Alembic commands ###
