"""empty message

Revision ID: 13480c896c0e
Revises: bcd28e51cbeb
Create Date: 2018-08-26 17:29:03.450380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13480c896c0e'
down_revision = 'bcd28e51cbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('added', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_annotation_added'), 'annotation', ['added'], unique=False)
    op.drop_index('ix_annotation_modified', table_name='annotation')
    op.drop_constraint('annotation_ibfk_2', 'annotation', type_='foreignkey')
    op.create_foreign_key(None, 'annotation', 'annotation_version', ['head_id'], ['id'])
    op.drop_column('annotation', 'modified')
    op.add_column('annotation_version', sa.Column('modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_annotation_version_modified'), 'annotation_version', ['modified'], unique=False)
    op.drop_index('ix_annotation_version_added', table_name='annotation_version')
    op.drop_column('annotation_version', 'added')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_version', sa.Column('added', mysql.DATETIME(), nullable=True))
    op.create_index('ix_annotation_version_added', 'annotation_version', ['added'], unique=False)
    op.drop_index(op.f('ix_annotation_version_modified'), table_name='annotation_version')
    op.drop_column('annotation_version', 'modified')
    op.add_column('annotation', sa.Column('modified', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.create_foreign_key('annotation_ibfk_2', 'annotation', 'annotation', ['head_id'], ['id'])
    op.create_index('ix_annotation_modified', 'annotation', ['modified'], unique=False)
    op.drop_index(op.f('ix_annotation_added'), table_name='annotation')
    op.drop_column('annotation', 'added')
    # ### end Alembic commands ###
