"""empty message

Revision ID: 17f5476c14a0
Revises: ae2143991b0f
Create Date: 2018-10-12 09:39:46.571345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f5476c14a0'
down_revision = 'ae2143991b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=127), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('wikipedia', sa.String(length=127), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_request_approved'), 'tag_request', ['approved'], unique=False)
    op.create_index(op.f('ix_tag_request_rejected'), 'tag_request', ['rejected'], unique=False)
    op.create_index(op.f('ix_tag_request_requested'), 'tag_request', ['requested'], unique=False)
    op.create_index(op.f('ix_tag_request_requester_id'), 'tag_request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tag_request_tag'), 'tag_request', ['tag'], unique=False)
    op.create_index(op.f('ix_tag_request_weight'), 'tag_request', ['weight'], unique=False)
    op.create_table('tag_request_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_request_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_request_id'], ['tag_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_request_vote_tag_request_id'), 'tag_request_vote', ['tag_request_id'], unique=False)
    op.create_index(op.f('ix_tag_request_vote_user_id'), 'tag_request_vote', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_request_vote_user_id'), table_name='tag_request_vote')
    op.drop_index(op.f('ix_tag_request_vote_tag_request_id'), table_name='tag_request_vote')
    op.drop_table('tag_request_vote')
    op.drop_index(op.f('ix_tag_request_weight'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_tag'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_requester_id'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_requested'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_rejected'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_approved'), table_name='tag_request')
    op.drop_table('tag_request')
    # ### end Alembic commands ###
