"""empty message

Revision ID: 227224fa9b59
Revises: eb799e906153
Create Date: 2018-08-23 14:25:44.164870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227224fa9b59'
down_revision = 'eb799e906153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('added', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_annotation_added'), 'annotation', ['added'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_added'), table_name='annotation')
    op.drop_column('annotation', 'added')
    # ### end Alembic commands ###
