"""empty message

Revision ID: 2970b6fdf939
Revises: 384c7334912b
Create Date: 2018-10-24 12:11:33.339262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2970b6fdf939'
down_revision = '384c7334912b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_flag_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_flag_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thrower_id', sa.Integer(), nullable=True),
    sa.Column('time_thrown', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thrower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_flag_id'], ['user_flag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_flag_event_thrower_id'), 'user_flag_event', ['thrower_id'], unique=False)
    op.create_index(op.f('ix_user_flag_event_user_flag_id'), 'user_flag_event', ['user_flag_id'], unique=False)
    op.create_index(op.f('ix_user_flag_event_user_id'), 'user_flag_event', ['user_id'], unique=False)
    op.drop_index('ix_user_displayname', table_name='user')
    op.create_index(op.f('ix_user_displayname'), 'user', ['displayname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_displayname'), table_name='user')
    op.create_index('ix_user_displayname', 'user', ['displayname'], unique=True)
    op.drop_index(op.f('ix_user_flag_event_user_id'), table_name='user_flag_event')
    op.drop_index(op.f('ix_user_flag_event_user_flag_id'), table_name='user_flag_event')
    op.drop_index(op.f('ix_user_flag_event_thrower_id'), table_name='user_flag_event')
    op.drop_table('user_flag_event')
    op.drop_table('user_flag')
    # ### end Alembic commands ###
