"""empty message

Revision ID: 2d4bfc2aa24e
Revises: 695dbc5fc243
Create Date: 2018-08-30 19:41:17.414992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4bfc2aa24e'
down_revision = '695dbc5fc243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reputation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reputation')
    # ### end Alembic commands ###
