"""empty message

Revision ID: 2f7b67f8c598
Revises: 13480c896c0e
Create Date: 2018-08-28 20:56:30.464230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7b67f8c598'
down_revision = '13480c896c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('hash_id', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_annotation_hash_id'), 'annotation', ['hash_id'], unique=False)
    op.add_column('annotation_version', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('annotation_version', sa.Column('hash_id', sa.String(length=40), nullable=True))
    op.add_column('annotation_version', sa.Column('pointer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_annotation_version_author_id'), 'annotation_version', ['author_id'], unique=False)
    op.create_index(op.f('ix_annotation_version_hash_id'), 'annotation_version', ['hash_id'], unique=False)
    op.create_index(op.f('ix_annotation_version_pointer_id'), 'annotation_version', ['pointer_id'], unique=False)
    op.create_foreign_key(None, 'annotation_version', 'annotation', ['pointer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_version', type_='foreignkey')
    op.drop_index(op.f('ix_annotation_version_pointer_id'), table_name='annotation_version')
    op.drop_index(op.f('ix_annotation_version_hash_id'), table_name='annotation_version')
    op.drop_index(op.f('ix_annotation_version_author_id'), table_name='annotation_version')
    op.drop_column('annotation_version', 'pointer_id')
    op.drop_column('annotation_version', 'hash_id')
    op.drop_column('annotation_version', 'author_id')
    op.drop_index(op.f('ix_annotation_hash_id'), table_name='annotation')
    op.drop_column('annotation', 'hash_id')
    # ### end Alembic commands ###
