"""empty message

Revision ID: 3837f36684dd
Revises: 44c115b44601
Create Date: 2018-10-30 15:58:18.717384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3837f36684dd'
down_revision = '44c115b44601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_request_vote', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('edit_vote', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('tag_request_vote', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('vote', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'time')
    op.drop_column('tag_request_vote', 'time')
    op.drop_column('edit_vote', 'time')
    op.drop_column('book_request_vote', 'time')
    # ### end Alembic commands ###
