"""empty message

Revision ID: 3879e573e2e5
Revises: bdc6ddf99481
Create Date: 2018-09-27 13:12:21.288008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3879e573e2e5'
down_revision = 'bdc6ddf99481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_tag', table_name='tag')
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.create_index('ix_tag_tag', 'tag', ['tag'], unique=False)
    # ### end Alembic commands ###
