"""empty message

Revision ID: 3b242efa57d7
Revises: 3837f36684dd
Create Date: 2018-10-30 16:04:46.027915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b242efa57d7'
down_revision = '3837f36684dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_event', sa.Column('hash_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_event', 'hash_id')
    # ### end Alembic commands ###
