"""empty message

Revision ID: 3ead38382ff7
Revises: 2f7b67f8c598
Create Date: 2018-08-28 21:01:02.495839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ead38382ff7'
down_revision = '2f7b67f8c598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_annotation_hash_id', table_name='annotation')
    op.drop_column('annotation', 'hash_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('hash_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True))
    op.create_index('ix_annotation_hash_id', 'annotation', ['hash_id'], unique=False)
    # ### end Alembic commands ###
