"""empty message

Revision ID: 3ec87b0fd763
Revises: abf5e3d90bd0
Create Date: 2018-07-12 15:36:46.035674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec87b0fd763'
down_revision = 'abf5e3d90bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('ident', sa.String(length=20), nullable=True),
    sa.Column('ident_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_ident'), 'page', ['ident'], unique=False)
    op.create_index(op.f('ix_page_page_number'), 'page', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_page_number'), table_name='page')
    op.drop_index(op.f('ix_page_ident'), table_name='page')
    op.drop_table('page')
    # ### end Alembic commands ###
