"""empty message

Revision ID: 448539db4623
Revises: ef1e44b845db
Create Date: 2018-11-09 11:35:22.943703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448539db4623'
down_revision = 'ef1e44b845db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_version', sa.Column('edit_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_version', 'edit_reason')
    # ### end Alembic commands ###
