"""empty message

Revision ID: 5b391475281c
Revises: 2970b6fdf939
Create Date: 2018-10-24 12:32:31.205562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b391475281c'
down_revision = '2970b6fdf939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_flag_event', sa.Column('resolved', sa.DateTime(), nullable=True))
    op.add_column('user_flag_event', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_flag_event_resolved_by'), 'user_flag_event', ['resolved_by'], unique=False)
    op.create_foreign_key(None, 'user_flag_event', 'user', ['resolved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_flag_event', type_='foreignkey')
    op.drop_index(op.f('ix_user_flag_event_resolved_by'), table_name='user_flag_event')
    op.drop_column('user_flag_event', 'resolved_by')
    op.drop_column('user_flag_event', 'resolved')
    # ### end Alembic commands ###
