"""empty message

Revision ID: 695dbc5fc243
Revises: cc25bf90e82e
Create Date: 2018-08-30 15:10:18.535633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695dbc5fc243'
down_revision = 'cc25bf90e82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'annotation', 'annotation_version', ['head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation', type_='foreignkey')
    op.drop_column('annotation', 'head_id')
    # ### end Alembic commands ###
