"""empty message

Revision ID: 6f8f6fb0b43b
Revises: b809259ad187
Create Date: 2018-07-21 09:08:09.090191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8f6fb0b43b'
down_revision = 'b809259ad187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('break', sa.Column('page_num', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_break_page_num'), 'break', ['page_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_break_page_num'), table_name='break')
    op.drop_column('break', 'page_num')
    # ### end Alembic commands ###
