"""empty message

Revision ID: 71d7f2b938ed
Revises: bdf8dd649091
Create Date: 2018-10-02 13:14:46.206590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d7f2b938ed'
down_revision = 'bdf8dd649091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'bio')
    # ### end Alembic commands ###
