"""empty message

Revision ID: 78ee36500b23
Revises: c19051384ff3
Create Date: 2018-07-13 11:49:51.200241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ee36500b23'
down_revision = 'c19051384ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('page_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_page_page_number'), 'page', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_page_number'), table_name='page')
    op.drop_column('page', 'page_number')
    # ### end Alembic commands ###
