"""empty message

Revision ID: 7914b1837739
Revises: 3ead38382ff7
Create Date: 2018-08-29 17:30:21.135243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7914b1837739'
down_revision = '3ead38382ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('edit_pending', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_annotation_edit_pending'), 'annotation', ['edit_pending'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_edit_pending'), table_name='annotation')
    op.drop_column('annotation', 'edit_pending')
    # ### end Alembic commands ###
