"""empty message

Revision ID: 82552b8c67a2
Revises: b5ea58bb3d24
Create Date: 2018-07-08 16:58:23.669515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82552b8c67a2'
down_revision = 'b5ea58bb3d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('death_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_author_death_date'), 'author', ['death_date'], unique=False)
    op.drop_index('ix_author_birth_year', table_name='author')
    op.drop_column('author', 'birth_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('birth_year', sa.DATE(), nullable=True))
    op.create_index('ix_author_birth_year', 'author', ['birth_year'], unique=False)
    op.drop_index(op.f('ix_author_death_date'), table_name='author')
    op.drop_column('author', 'death_date')
    # ### end Alembic commands ###
