"""empty message

Revision ID: 8c2714cd3d80
Revises: 17f5476c14a0
Create Date: 2018-10-12 14:44:44.831665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2714cd3d80'
down_revision = '17f5476c14a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_request', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tag_request_tag_id'), 'tag_request', ['tag_id'], unique=False)
    op.create_foreign_key(None, 'tag_request', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_request', type_='foreignkey')
    op.drop_index(op.f('ix_tag_request_tag_id'), table_name='tag_request')
    op.drop_column('tag_request', 'tag_id')
    # ### end Alembic commands ###
