"""empty message

Revision ID: 9b1e6075cd91
Revises: 5b391475281c
Create Date: 2018-10-27 08:24:28.213950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1e6075cd91'
down_revision = '5b391475281c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation_flag_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation_flag_id', sa.Integer(), nullable=True),
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('thrower_id', sa.Integer(), nullable=True),
    sa.Column('time_thrown', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_flag_id'], ['annotation_flag.id'], ),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thrower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_flag_event_annotation_flag_id'), 'annotation_flag_event', ['annotation_flag_id'], unique=False)
    op.create_index(op.f('ix_annotation_flag_event_annotation_id'), 'annotation_flag_event', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_flag_event_resolved_by'), 'annotation_flag_event', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_annotation_flag_event_thrower_id'), 'annotation_flag_event', ['thrower_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_flag_event_thrower_id'), table_name='annotation_flag_event')
    op.drop_index(op.f('ix_annotation_flag_event_resolved_by'), table_name='annotation_flag_event')
    op.drop_index(op.f('ix_annotation_flag_event_annotation_id'), table_name='annotation_flag_event')
    op.drop_index(op.f('ix_annotation_flag_event_annotation_flag_id'), table_name='annotation_flag_event')
    op.drop_table('annotation_flag_event')
    op.drop_table('annotation_flag')
    # ### end Alembic commands ###
