"""empty message

Revision ID: 9c501362c4c6
Revises: b30a6b433330
Create Date: 2018-11-03 08:42:27.744603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c501362c4c6'
down_revision = 'b30a6b433330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.add_column('user_followers', sa.Column('follower_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_followers_ibfk_1', 'user_followers', type_='foreignkey')
    op.create_foreign_key(None, 'user_followers', 'user', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'user_followers', 'user', ['follower_id'], ['id'])
    op.drop_column('user_followers', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_followers', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_followers', type_='foreignkey')
    op.drop_constraint(None, 'user_followers', type_='foreignkey')
    op.create_foreign_key('user_followers_ibfk_1', 'user_followers', 'user', ['user_id'], ['id'])
    op.drop_column('user_followers', 'follower_id')
    op.drop_column('user_followers', 'followed_id')
    # ### end Alembic commands ###
