"""empty message

Revision ID: ae2143991b0f
Revises: 6f6ddcb47ee1
Create Date: 2018-10-10 13:27:12.354052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2143991b0f'
down_revision = '6f6ddcb47ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_request', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_request', 'description')
    # ### end Alembic commands ###
