"""empty message

Revision ID: b6b30b1aff2a
Revises: 546c5d7bcdca
Create Date: 2018-07-15 09:21:44.779308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b30b1aff2a'
down_revision = '546c5d7bcdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('meta_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'meta_data')
    # ### end Alembic commands ###
