"""empty message

Revision ID: bdc6ddf99481
Revises: c563aac7923f
Create Date: 2018-09-26 16:50:02.663163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc6ddf99481'
down_revision = 'c563aac7923f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_version', sa.Column('pointer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_annotation_version_pointer_id'), 'annotation_version', ['pointer_id'], unique=False)
    op.create_foreign_key(None, 'annotation_version', 'annotation', ['pointer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_version', type_='foreignkey')
    op.drop_index(op.f('ix_annotation_version_pointer_id'), table_name='annotation_version')
    op.drop_column('annotation_version', 'pointer_id')
    # ### end Alembic commands ###
