"""empty message

Revision ID: bdf8dd649091
Revises: 3879e573e2e5
Create Date: 2018-09-27 20:29:50.771501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf8dd649091'
down_revision = '3879e573e2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'admin')
    # ### end Alembic commands ###
