"""empty message

Revision ID: be4f032af9f1
Revises: 3b242efa57d7
Create Date: 2018-10-31 13:30:15.647914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be4f032af9f1'
down_revision = '3b242efa57d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_type', sa.Column('code', sa.String(length=64), nullable=True))
    op.add_column('notification_type', sa.Column('description', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_notification_type_code'), 'notification_type', ['code'], unique=False)
    op.drop_index('ix_notification_type_event', table_name='notification_type')
    op.drop_column('notification_type', 'event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_type', sa.Column('event', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.create_index('ix_notification_type_event', 'notification_type', ['event'], unique=False)
    op.drop_index(op.f('ix_notification_type_code'), table_name='notification_type')
    op.drop_column('notification_type', 'description')
    op.drop_column('notification_type', 'code')
    # ### end Alembic commands ###
