"""empty message

Revision ID: c19051384ff3
Revises: d78477d26c6d
Create Date: 2018-07-13 10:51:40.341820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c19051384ff3'
down_revision = 'd78477d26c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_page_page_number', table_name='page')
    op.drop_column('page', 'page_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('page_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_page_page_number', 'page', ['page_number'], unique=False)
    # ### end Alembic commands ###
