"""empty message

Revision ID: c9f2a418cde7
Revises: 001c56f6f348
Create Date: 2018-10-05 14:08:31.707922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f2a418cde7'
down_revision = '001c56f6f348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'annotation_version', 'line', ['last_line_num'], ['l_num'])
    op.create_foreign_key(None, 'annotation_version', 'line', ['first_line_num'], ['l_num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation_version', type_='foreignkey')
    op.drop_constraint(None, 'annotation_version', type_='foreignkey')
    op.drop_column('annotation', 'active')
    # ### end Alembic commands ###
