"""empty message

Revision ID: cce1cf257bd6
Revises: 78ee36500b23
Create Date: 2018-07-13 13:46:45.124684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce1cf257bd6'
down_revision = '78ee36500b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('page_ibfk_3', 'page', type_='foreignkey')
    op.drop_constraint('page_ibfk_2', 'page', type_='foreignkey')
    op.create_foreign_key(None, 'page', 'position', ['stop_id'], ['position'])
    op.create_foreign_key(None, 'page', 'position', ['start_id'], ['position'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.create_foreign_key('page_ibfk_2', 'page', 'position', ['start_id'], ['id'])
    op.create_foreign_key('page_ibfk_3', 'page', 'position', ['stop_id'], ['id'])
    # ### end Alembic commands ###
