"""empty message

Revision ID: cf0de5dbd6a1
Revises: 6f8f6fb0b43b
Create Date: 2018-07-22 10:41:17.372296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0de5dbd6a1'
down_revision = '6f8f6fb0b43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('sort_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_book_sort_name'), 'book', ['sort_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_sort_name'), table_name='book')
    op.drop_column('book', 'sort_name')
    # ### end Alembic commands ###
