"""empty message

Revision ID: d78477d26c6d
Revises: 3ec87b0fd763
Create Date: 2018-07-12 15:48:46.221420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd78477d26c6d'
down_revision = '3ec87b0fd763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('start_id', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('stop_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_page_book_id'), 'page', ['book_id'], unique=False)
    op.create_foreign_key(None, 'page', 'book', ['book_id'], ['id'])
    op.create_foreign_key(None, 'page', 'position', ['start_id'], ['id'])
    op.create_foreign_key(None, 'page', 'position', ['stop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_index(op.f('ix_page_book_id'), table_name='page')
    op.drop_column('page', 'stop_id')
    op.drop_column('page', 'start_id')
    op.drop_column('page', 'book_id')
    # ### end Alembic commands ###
