"""empty message

Revision ID: d9273e15f7b0
Revises: a30c226f1197
Create Date: 2019-06-07 13:58:21.118006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9273e15f7b0'
down_revision = 'a30c226f1197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit', sa.Column('toc_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_edit_toc_id'), 'edit', ['toc_id'], unique=False)
    op.create_foreign_key(None, 'edit', 'toc', ['toc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'edit', type_='foreignkey')
    op.drop_index(op.f('ix_edit_toc_id'), table_name='edit')
    op.drop_column('edit', 'toc_id')
    # ### end Alembic commands ###
