"""empty message

Revision ID: e5caf57dd47a
Revises: cce1cf257bd6
Create Date: 2018-07-13 15:53:09.762209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5caf57dd47a'
down_revision = 'cce1cf257bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('url', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_author_url'), 'author', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_url'), table_name='author')
    op.drop_column('author', 'url')
    # ### end Alembic commands ###
