"""empty message

Revision ID: e613ac45673d
Revises: e5caf57dd47a
Create Date: 2018-07-14 08:44:33.263981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e613ac45673d'
down_revision = 'e5caf57dd47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('ident_identifier', sa.String(length=128), nullable=True))
    op.add_column('page', sa.Column('ident_num_1', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('ident_num_2', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('ident_num_3', sa.Integer(), nullable=True))
    op.drop_column('page', 'ident_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('ident_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('page', 'ident_num_3')
    op.drop_column('page', 'ident_num_2')
    op.drop_column('page', 'ident_num_1')
    op.drop_column('page', 'ident_identifier')
    # ### end Alembic commands ###
