"""empty message

Revision ID: ef1e44b845db
Revises: b491a84ec6cf
Create Date: 2018-11-09 11:30:52.430093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1e44b845db'
down_revision = 'b491a84ec6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_version', sa.Column('edit_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_version', 'edit_num')
    # ### end Alembic commands ###
