"""empty message

Revision ID: f0ba55d30f42
Revises: 0c06324d7840
Create Date: 2018-08-29 19:25:52.442246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ba55d30f42'
down_revision = '0c06324d7840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_annotation_version_approved'), 'annotation_version', ['approved'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_version_approved'), table_name='annotation_version')
    # ### end Alembic commands ###
