"""empty message

Revision ID: f168e2595b97
Revises: 
Create Date: 2018-11-29 14:30:44.711083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f168e2595b97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_added'), 'author', ['added'], unique=False)
    op.create_index(op.f('ix_author_birth_date'), 'author', ['birth_date'], unique=False)
    op.create_index(op.f('ix_author_death_date'), 'author', ['death_date'], unique=False)
    op.create_index(op.f('ix_author_first_name'), 'author', ['first_name'], unique=False)
    op.create_index(op.f('ix_author_last_name'), 'author', ['last_name'], unique=False)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_index(op.f('ix_author_url'), 'author', ['url'], unique=False)
    op.create_table('line_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=12), nullable=True),
    sa.Column('display', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_label_label'), 'line_label', ['label'], unique=False)
    op.create_table('notification_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_type_code'), 'notification_type', ['code'], unique=False)
    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('right', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_right_right'), 'right', ['right'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('displayname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('cumulative_negative', sa.Integer(), nullable=True),
    sa.Column('cumulative_positive', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_displayname'), 'user', ['displayname'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('author_followers',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('sort_title', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published', sa.Date(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_author_id'), 'book', ['author_id'], unique=False)
    op.create_index(op.f('ix_book_sort_title'), 'book', ['sort_title'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_index(op.f('ix_book_url'), 'book', ['url'], unique=False)
    op.create_table('conferred_rights',
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['right_id'], ['right.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('notification_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('seen_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('information', sa.Text(), nullable=True),
    sa.Column('hash_id', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_followers',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('tag_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=127), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('wikipedia', sa.String(length=127), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_request_approved'), 'tag_request', ['approved'], unique=False)
    op.create_index(op.f('ix_tag_request_rejected'), 'tag_request', ['rejected'], unique=False)
    op.create_index(op.f('ix_tag_request_requested'), 'tag_request', ['requested'], unique=False)
    op.create_index(op.f('ix_tag_request_requester_id'), 'tag_request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tag_request_tag'), 'tag_request', ['tag'], unique=False)
    op.create_index(op.f('ix_tag_request_tag_id'), 'tag_request', ['tag_id'], unique=False)
    op.create_index(op.f('ix_tag_request_weight'), 'tag_request', ['weight'], unique=False)
    op.create_table('user_flag_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_flag_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thrower_id', sa.Integer(), nullable=True),
    sa.Column('time_thrown', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thrower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_flag_id'], ['user_flag.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_flag_event_resolved_by'), 'user_flag_event', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_user_flag_event_thrower_id'), 'user_flag_event', ['thrower_id'], unique=False)
    op.create_index(op.f('ix_user_flag_event_user_flag_id'), 'user_flag_event', ['user_flag_id'], unique=False)
    op.create_index(op.f('ix_user_flag_event_user_id'), 'user_flag_event', ['user_id'], unique=False)
    op.create_table('user_followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('edit_pending', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['annotator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_added'), 'annotation', ['added'], unique=False)
    op.create_index(op.f('ix_annotation_annotator_id'), 'annotation', ['annotator_id'], unique=False)
    op.create_index(op.f('ix_annotation_book_id'), 'annotation', ['book_id'], unique=False)
    op.create_index(op.f('ix_annotation_edit_pending'), 'annotation', ['edit_pending'], unique=False)
    op.create_index(op.f('ix_annotation_locked'), 'annotation', ['locked'], unique=False)
    op.create_table('book_followers',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('book_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=127), nullable=True),
    sa.Column('author', sa.String(length=127), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('wikipedia', sa.String(length=127), nullable=True),
    sa.Column('gutenberg', sa.String(length=127), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('requested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_request_approved'), 'book_request', ['approved'], unique=False)
    op.create_index(op.f('ix_book_request_author'), 'book_request', ['author'], unique=False)
    op.create_index(op.f('ix_book_request_book_id'), 'book_request', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_request_rejected'), 'book_request', ['rejected'], unique=False)
    op.create_index(op.f('ix_book_request_requested'), 'book_request', ['requested'], unique=False)
    op.create_index(op.f('ix_book_request_requester_id'), 'book_request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_book_request_title'), 'book_request', ['title'], unique=False)
    op.create_index(op.f('ix_book_request_weight'), 'book_request', ['weight'], unique=False)
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('line_num', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('lvl1', sa.Integer(), nullable=True),
    sa.Column('lvl2', sa.Integer(), nullable=True),
    sa.Column('lvl3', sa.Integer(), nullable=True),
    sa.Column('lvl4', sa.Integer(), nullable=True),
    sa.Column('em_id', sa.Integer(), nullable=True),
    sa.Column('line', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['em_id'], ['line_label.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['line_label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_book_id'), 'line', ['book_id'], unique=False)
    op.create_index(op.f('ix_line_em_id'), 'line', ['em_id'], unique=False)
    op.create_index(op.f('ix_line_label_id'), 'line', ['label_id'], unique=False)
    op.create_index(op.f('ix_line_line_num'), 'line', ['line_num'], unique=False)
    op.create_index(op.f('ix_line_lvl1'), 'line', ['lvl1'], unique=False)
    op.create_index(op.f('ix_line_lvl2'), 'line', ['lvl2'], unique=False)
    op.create_index(op.f('ix_line_lvl3'), 'line', ['lvl3'], unique=False)
    op.create_index(op.f('ix_line_lvl4'), 'line', ['lvl4'], unique=False)
    op.create_table('tag_request_followers',
    sa.Column('tag_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_request_id'], ['tag_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('tag_request_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tag_request_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_request_id'], ['tag_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_request_vote_tag_request_id'), 'tag_request_vote', ['tag_request_id'], unique=False)
    op.create_index(op.f('ix_tag_request_vote_user_id'), 'tag_request_vote', ['user_id'], unique=False)
    op.create_table('annotation_flag_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation_flag_id', sa.Integer(), nullable=True),
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('thrower_id', sa.Integer(), nullable=True),
    sa.Column('time_thrown', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_flag_id'], ['annotation_flag.id'], ),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thrower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_flag_event_annotation_flag_id'), 'annotation_flag_event', ['annotation_flag_id'], unique=False)
    op.create_index(op.f('ix_annotation_flag_event_annotation_id'), 'annotation_flag_event', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_annotation_flag_event_resolved_by'), 'annotation_flag_event', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_annotation_flag_event_thrower_id'), 'annotation_flag_event', ['thrower_id'], unique=False)
    op.create_table('annotation_followers',
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('book_request_followers',
    sa.Column('book_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_request_id'], ['book_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('book_request_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_request_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_request_id'], ['book_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_request_vote_book_request_id'), 'book_request_vote', ['book_request_id'], unique=False)
    op.create_index(op.f('ix_book_request_vote_user_id'), 'book_request_vote', ['user_id'], unique=False)
    op.create_table('edit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('editor_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('hash_id', sa.String(length=40), nullable=True),
    sa.Column('edit_num', sa.Integer(), nullable=True),
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('first_line_num', sa.Integer(), nullable=True),
    sa.Column('last_line_num', sa.Integer(), nullable=True),
    sa.Column('first_char_idx', sa.Integer(), nullable=True),
    sa.Column('last_char_idx', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edit_reason', sa.String(length=255), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['editor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['first_line_num'], ['line.line_num'], ),
    sa.ForeignKeyConstraint(['last_line_num'], ['line.line_num'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_annotation_id'), 'edit', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_edit_approved'), 'edit', ['approved'], unique=False)
    op.create_index(op.f('ix_edit_book_id'), 'edit', ['book_id'], unique=False)
    op.create_index(op.f('ix_edit_current'), 'edit', ['current'], unique=False)
    op.create_index(op.f('ix_edit_editor_id'), 'edit', ['editor_id'], unique=False)
    op.create_index(op.f('ix_edit_hash_id'), 'edit', ['hash_id'], unique=False)
    op.create_index(op.f('ix_edit_last_line_num'), 'edit', ['last_line_num'], unique=False)
    op.create_index(op.f('ix_edit_modified'), 'edit', ['modified'], unique=False)
    op.create_index(op.f('ix_edit_rejected'), 'edit', ['rejected'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('annotation_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vote_annotation_id'), 'vote', ['annotation_id'], unique=False)
    op.create_index(op.f('ix_vote_user_id'), 'vote', ['user_id'], unique=False)
    op.create_table('edit_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edit_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_vote_edit_id'), 'edit_vote', ['edit_id'], unique=False)
    op.create_index(op.f('ix_edit_vote_user_id'), 'edit_vote', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('edit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_index(op.f('ix_edit_vote_user_id'), table_name='edit_vote')
    op.drop_index(op.f('ix_edit_vote_edit_id'), table_name='edit_vote')
    op.drop_table('edit_vote')
    op.drop_index(op.f('ix_vote_user_id'), table_name='vote')
    op.drop_index(op.f('ix_vote_annotation_id'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_edit_rejected'), table_name='edit')
    op.drop_index(op.f('ix_edit_modified'), table_name='edit')
    op.drop_index(op.f('ix_edit_last_line_num'), table_name='edit')
    op.drop_index(op.f('ix_edit_hash_id'), table_name='edit')
    op.drop_index(op.f('ix_edit_editor_id'), table_name='edit')
    op.drop_index(op.f('ix_edit_current'), table_name='edit')
    op.drop_index(op.f('ix_edit_book_id'), table_name='edit')
    op.drop_index(op.f('ix_edit_approved'), table_name='edit')
    op.drop_index(op.f('ix_edit_annotation_id'), table_name='edit')
    op.drop_table('edit')
    op.drop_index(op.f('ix_book_request_vote_user_id'), table_name='book_request_vote')
    op.drop_index(op.f('ix_book_request_vote_book_request_id'), table_name='book_request_vote')
    op.drop_table('book_request_vote')
    op.drop_table('book_request_followers')
    op.drop_table('annotation_followers')
    op.drop_index(op.f('ix_annotation_flag_event_thrower_id'), table_name='annotation_flag_event')
    op.drop_index(op.f('ix_annotation_flag_event_resolved_by'), table_name='annotation_flag_event')
    op.drop_index(op.f('ix_annotation_flag_event_annotation_id'), table_name='annotation_flag_event')
    op.drop_index(op.f('ix_annotation_flag_event_annotation_flag_id'), table_name='annotation_flag_event')
    op.drop_table('annotation_flag_event')
    op.drop_index(op.f('ix_tag_request_vote_user_id'), table_name='tag_request_vote')
    op.drop_index(op.f('ix_tag_request_vote_tag_request_id'), table_name='tag_request_vote')
    op.drop_table('tag_request_vote')
    op.drop_table('tag_request_followers')
    op.drop_index(op.f('ix_line_lvl4'), table_name='line')
    op.drop_index(op.f('ix_line_lvl3'), table_name='line')
    op.drop_index(op.f('ix_line_lvl2'), table_name='line')
    op.drop_index(op.f('ix_line_lvl1'), table_name='line')
    op.drop_index(op.f('ix_line_line_num'), table_name='line')
    op.drop_index(op.f('ix_line_label_id'), table_name='line')
    op.drop_index(op.f('ix_line_em_id'), table_name='line')
    op.drop_index(op.f('ix_line_book_id'), table_name='line')
    op.drop_table('line')
    op.drop_index(op.f('ix_book_request_weight'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_title'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_requester_id'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_requested'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_rejected'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_book_id'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_author'), table_name='book_request')
    op.drop_index(op.f('ix_book_request_approved'), table_name='book_request')
    op.drop_table('book_request')
    op.drop_table('book_followers')
    op.drop_index(op.f('ix_annotation_locked'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_edit_pending'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_book_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_annotator_id'), table_name='annotation')
    op.drop_index(op.f('ix_annotation_added'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_table('user_followers')
    op.drop_index(op.f('ix_user_flag_event_user_id'), table_name='user_flag_event')
    op.drop_index(op.f('ix_user_flag_event_user_flag_id'), table_name='user_flag_event')
    op.drop_index(op.f('ix_user_flag_event_thrower_id'), table_name='user_flag_event')
    op.drop_index(op.f('ix_user_flag_event_resolved_by'), table_name='user_flag_event')
    op.drop_table('user_flag_event')
    op.drop_index(op.f('ix_tag_request_weight'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_tag_id'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_tag'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_requester_id'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_requested'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_rejected'), table_name='tag_request')
    op.drop_index(op.f('ix_tag_request_approved'), table_name='tag_request')
    op.drop_table('tag_request')
    op.drop_table('tag_followers')
    op.drop_table('notification_event')
    op.drop_table('conferred_rights')
    op.drop_index(op.f('ix_book_url'), table_name='book')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_sort_title'), table_name='book')
    op.drop_index(op.f('ix_book_author_id'), table_name='book')
    op.drop_table('book')
    op.drop_table('author_followers')
    op.drop_table('user_flag')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_displayname'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_right_right'), table_name='right')
    op.drop_table('right')
    op.drop_index(op.f('ix_notification_type_code'), table_name='notification_type')
    op.drop_table('notification_type')
    op.drop_index(op.f('ix_line_label_label'), table_name='line_label')
    op.drop_table('line_label')
    op.drop_index(op.f('ix_author_url'), table_name='author')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_last_name'), table_name='author')
    op.drop_index(op.f('ix_author_first_name'), table_name='author')
    op.drop_index(op.f('ix_author_death_date'), table_name='author')
    op.drop_index(op.f('ix_author_birth_date'), table_name='author')
    op.drop_index(op.f('ix_author_added'), table_name='author')
    op.drop_table('author')
    op.drop_table('annotation_flag')
    # ### end Alembic commands ###
