"""empty message

Revision ID: f5b55959727c
Revises: c1053ce27a83
Create Date: 2018-09-01 14:41:18.812547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b55959727c'
down_revision = 'c1053ce27a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cumulative_negative', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('cumulative_positive', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cumulative_positive')
    op.drop_column('user', 'cumulative_negative')
    # ### end Alembic commands ###
