"""empty message

Revision ID: f779da4b3592
Revises: 
Create Date: 2018-07-28 16:16:41.818517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f779da4b3592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('ts_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_birth_date'), 'author', ['birth_date'], unique=False)
    op.create_index(op.f('ix_author_death_date'), 'author', ['death_date'], unique=False)
    op.create_index(op.f('ix_author_first_name'), 'author', ['first_name'], unique=False)
    op.create_index(op.f('ix_author_last_name'), 'author', ['last_name'], unique=False)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_index(op.f('ix_author_ts_added'), 'author', ['ts_added'], unique=False)
    op.create_index(op.f('ix_author_url'), 'author', ['url'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Date(), nullable=True),
    sa.Column('ts_added', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('sort_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_author_id'), 'book', ['author_id'], unique=False)
    op.create_index(op.f('ix_book_sort_name'), 'book', ['sort_name'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_index(op.f('ix_book_url'), 'book', ['url'], unique=False)
    op.create_table('break',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('book_num', sa.Integer(), nullable=True),
    sa.Column('part_num', sa.Integer(), nullable=True),
    sa.Column('ch_num', sa.Integer(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.Column('break_title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_book_id'), 'break', ['book_id'], unique=False)
    op.create_index(op.f('ix_break_book_num'), 'break', ['book_num'], unique=False)
    op.create_index(op.f('ix_break_ch_num'), 'break', ['ch_num'], unique=False)
    op.create_index(op.f('ix_break_page_num'), 'break', ['page_num'], unique=False)
    op.create_index(op.f('ix_break_part_num'), 'break', ['part_num'], unique=False)
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('page', mysql.LONGTEXT(), nullable=True),
    sa.Column('page_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_book_id'), 'page', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_book_id'), table_name='page')
    op.drop_table('page')
    op.drop_index(op.f('ix_break_part_num'), table_name='break')
    op.drop_index(op.f('ix_break_page_num'), table_name='break')
    op.drop_index(op.f('ix_break_ch_num'), table_name='break')
    op.drop_index(op.f('ix_break_book_num'), table_name='break')
    op.drop_index(op.f('ix_break_book_id'), table_name='break')
    op.drop_table('break')
    op.drop_index(op.f('ix_book_url'), table_name='book')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_sort_name'), table_name='book')
    op.drop_index(op.f('ix_book_author_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_author_url'), table_name='author')
    op.drop_index(op.f('ix_author_ts_added'), table_name='author')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_last_name'), table_name='author')
    op.drop_index(op.f('ix_author_first_name'), table_name='author')
    op.drop_index(op.f('ix_author_death_date'), table_name='author')
    op.drop_index(op.f('ix_author_birth_date'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
