"""empty message

Revision ID: f86dd6d64b3e
Revises: f5b55959727c
Create Date: 2018-09-08 07:45:36.327801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86dd6d64b3e'
down_revision = 'f5b55959727c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'description')
    # ### end Alembic commands ###
