"""empty message

Revision ID: f8f795ffadb5
Revises: 0b219cfc6712
Create Date: 2018-11-15 09:54:08.744469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8f795ffadb5'
down_revision = '0b219cfc6712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_request_followers',
    sa.Column('tag_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_request_id'], ['tag_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('book_request_followers',
    sa.Column('book_request_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_request_id'], ['book_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_request_followers')
    op.drop_table('tag_request_followers')
    # ### end Alembic commands ###
