INSERT INTO notification_type (code, description) VALUES
    ("annotation_downvote", "downvote on annotation"),
    ("annotation_locked", "annotation locked from editing"),
    ("annotation_unlocked", "annotation unlocked for editing"),
    ("annotation_upvote", "upvote on annotation"),
    ("book_added", "approved book added"),
    ("book_approved", "book request approved"),
    ("book_rejected", "book request rejected"),
    ("book_request_downvote", "upvote on annotation"),
    ("book_request_upvote", "upvote on annotation"),
    ("edit_approved", "annotation edit approved"),
    ("edit_rejected", "annotation edit rejected"),
    ("new_annotation", "new annotation"),
    ("new_annotation_flag", "new annotation flag"),
    ("new_user_flag", "new user flag"),
    ("tag_approved", "tag approved"),
    ("tag_rejected", "tag rejected"),
    ("tag_request_downvote", "upvote on annotation"),
    ("tag_request_upvote", "upvote on annotation");
