INSERT INTO admin_right (`right`) VALUES
    ("approve_edits"),
    ("create_new_tags"),
    ("create_tags"),
    ("delete_annotations"),
    ("edit_bios"),
    ("edit_book_requests"),
    ("edit_lines"),
    ("edit_locked_annotations"),
    ("edit_summaries"),
    ("edit_tags"),
    ("immediate_edits"),
    ("lock_annotations"),
    ("lock_user_accounts"),
    ("lock_users"),
    ("review_edits"),
    ("use_restricted_tags"),
    ("view_deleted_annotations");
