source /home/malan/projects/icc/processor/sql/connection_enums.sql
source /home/malan/projects/icc/processor/sql/flags.sql
source /home/malan/projects/icc/processor/sql/line_enums.sql
source /home/malan/projects/icc/processor/sql/notification_enums.sql
source /home/malan/projects/icc/processor/sql/reputation_enums.sql
source /home/malan/projects/icc/processor/sql/rights.sql
source /home/malan/projects/icc/processor/sql/tags.sql
source /home/malan/projects/icc/processor/sql/texts.sql
source /home/malan/projects/icc/processor/sql/writers.sql
