insert into tag (tag, description, admin) values
    ("biblical", "For references to the bible", 0),
    ("definition", "For definitions of words not easily found (e.g., ancient words, specialized vocabulary, etc.)", 0),
    ("explanation", "For explanations of difficult passages", 0),
    ("homage", "For making explicit homages", 0),
    ("intertextuality", "For making explicit instances of intertextuality", 0),
    ("meter", "For analysis of particular deviations from standard meter", 0),
    ("mythology", "For references to mythology", 0),
    ("original", "For annotations from the original work", 1),
    ("political", "For explanation of political subtext and context", 0),
    ("cultural", "For explanation of cultural subtext and context", 0),
    ("reference", "For explanations of references to other works", 0),
    ("shakespeare", "For references to Shakespeare", 0),
    ("technical-issues", "For descriptions of complications with textual history (i.e., conflicting manuscripts, etc.)", 0),
    ("translation", "For translation of foreign phrases", 0),
    ("context", "For providing context to modern audiences", 0);
